### ISSUE TITLE
LWJGL Test program fails from jar

### ISSUE THREAD

**Issue by Sylvyrfysh** [kotlin-graphics/imgui#10]
Upon running the LWJGL test program from the provided jar, this exception occurs

Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(Unknown Source)
	at gln.program.Program.createShader(program.kt:173)
	at gln.program.Program.<init>(program.kt:100)
	at imgui.impl.LwjglGL3$ProgramA.<init>(LwjglGL3.kt:234)
	at imgui.impl.LwjglGL3.createDeviceObjects(LwjglGL3.kt:159)
	at imgui.impl.LwjglGL3.newFrame(LwjglGL3.kt:108)
	at s.TTest.loop(TTest.java:95)
	at s.TTest.run(TTest.java:53)
	at s.TTest.main(TTest.java:17)

Still a gradle noob, got the stuff to download but imports not showing up. This came up, looks like a GLN issue, but wasn't sure if it was your implementation or not. Let me know!

**Comment by elect86** [comment]
That's an old bug that has been long fixed.

However it seems it's still in the last release, I just published a [new one](https://github.com/kotlin-graphics/imgui/releases/tag/v1.53wip), try that

**Comment by Sylvyrfysh** [comment]
Works! Thanks for fixing so quickly, looking forward to trying this!

**Comment by elect86** [comment]
Glad to hear that. Have fun!
