### ISSUE TITLE
NoSuchMethodError trying to load natives for Imm32

### ISSUE THREAD

**Issue by mertcanekiz** [kotlin-graphics/imgui#102]
I am getting NoSuchMethodError while trying to call `ImGui.render()` and the stack trace is as follows: 

```
Exception in thread "main" java.lang.NoSuchMethodError: 'org.lwjgl.system.SharedLibrary org.lwjgl.system.Library.loadNative(java.lang.String)'
	at imgui.windowsIme.imm.<clinit>(imm.kt:15)
	at imgui.ImGuiStaticFunctions$imeSetInputScreenPosFn_Win32$1.invoke(static funcs.kt:1082)
	at imgui.ImGuiStaticFunctions$imeSetInputScreenPosFn_Win32$1.invoke(static funcs.kt)
	at imgui.imgui.imgui_main$DefaultImpls.endFrame(main.kt:347)
	at imgui.ImGui.endFrame(imgui.kt:95)
	at imgui.imgui.imgui_main$DefaultImpls.render(main.kt:423)
	at imgui.ImGui.render(imgui.kt:95)
	at melkorkt.imgui.ImGuiLayer.end(ImGuiLayer.kt:49)
	at melkorkt.core.Application.run(Application.kt:46)
	at melkorkt.core.MainKt.main(Main.kt:6)
```

I thought #99 might be related to this and I tried setting `MINECRAFT_BEHAVIORS` to true, but this does not seem to affect the result.

---
**Edit:** After trying to navigate around the source, I found that the `Library.loadNative("Imm32")` call is happening on this line (imm.kt:15). However, when I try to hover and go to declaration in IntelliJ, it only shows me these:

![image](https://user-images.githubusercontent.com/2145468/66669533-6c547280-ec60-11e9-8cd4-988d9d979208.png)

And there isn't a method with the signature `loadNative(String)` listed there, which seems to be the problem.

**Comment by Sylvyrfysh** [comment]
Which OS are you using?

**Comment by mertcanekiz** [comment]
I'm using Windows 10

**Comment by Sylvyrfysh** [comment]
Which branch are you on? Current master is using LWJGL 3.2.2, I see you're using 3.2.3. Internal LWJGL reworks require us to rework before moving to 3.2.3, but that's on the 1.73 branch

**Comment by mertcanekiz** [comment]
Yes, this is indeed caused by LWJGL 3.2.3 and switching to version 3.2.2 solves my problem. Thanks!

**Comment by elect86** [comment]
Hi Mertcan,

small info, we updated imgui to lwjgl 3.2.3, give it a try :)
