### ISSUE TITLE
java.lang.NoClassDefFoundError: gln/identifiers/GlProgram

### ISSUE THREAD

**Issue by tdgroot** [kotlin-graphics/imgui#103]
I'm really excited about the fact that there's a imgui port for Java/Kotlin. Unfortunately I have some problems getting everything up and running.

When I run my application, I see the error: 
```
Exception in thread "main" java.lang.NoClassDefFoundError: gln/identifiers/GlProgram
	at imgui.impl.ImplGL3.<init>(ImplGL3.kt:37)
	at MainKt.main(main.kt:18)
	at MainKt.main(main.kt)
```

What am I doing wrong here?

**main.kt**
``` java
import imgui.imgui.Context
import imgui.impl.ImplGL3
import imgui.impl2.ImplGlfw
import org.lwjgl.opengl.GL11.*
import uno.glfw.GlfwWindow
import uno.glfw.glfw

fun main() {
    glfw.init("3.3")

    var implGlfw: ImplGlfw
    var implGL3: ImplGL3

    val window = GlfwWindow(900, 600, "Kotlingame").apply {
        init()
        val context = Context(null)
        implGlfw = ImplGlfw(this)
        implGL3 = ImplGL3()
    }

    glClearColor(1f, 0f, 0f, 0f)

    window.loop {
        glClear(GL_COLOR_BUFFER_BIT)
    }
}
```

**build.gradle**
``` groovy
import org.gradle.internal.os.OperatingSystem

plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.3.41'
}

apply plugin: 'java'
apply plugin: 'application'

project.ext.lwjglVersion = "3.2.3"

switch (OperatingSystem.current()) {
    case OperatingSystem.LINUX:
        project.ext.lwjglNatives = "natives-linux"
        break
    case OperatingSystem.WINDOWS:
        project.ext.lwjglNatives = "natives-windows"
        break
}

version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven { url "https://dl.bintray.com/kotlin/kotlin-dev" }
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    compile 'com.github.kotlin-graphics:uno-sdk:v0.7.6'
    compile 'com.github.kotlin-graphics:imgui:1.71'

    implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")

    implementation "org.lwjgl:lwjgl"
    implementation "org.lwjgl:lwjgl-assimp"
    implementation "org.lwjgl:lwjgl-bgfx"
    implementation "org.lwjgl:lwjgl-glfw"
    implementation "org.lwjgl:lwjgl-nanovg"
    implementation "org.lwjgl:lwjgl-nuklear"
    implementation "org.lwjgl:lwjgl-openal"
    implementation "org.lwjgl:lwjgl-opengl"
    implementation "org.lwjgl:lwjgl-par"
    implementation "org.lwjgl:lwjgl-stb"
    implementation "org.lwjgl:lwjgl-vulkan"
    runtimeOnly "org.lwjgl:lwjgl::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-assimp::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-bgfx::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-glfw::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-nanovg::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-nuklear::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-openal::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-opengl::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-par::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-stb::$lwjglNatives"
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
```

**Comment by Sylvyrfysh** [comment]
Today  I do not have the time to deeply investigate this, I'll get to that tomorrow, but I can suggest a couple things that may fix this. Firstly, I believe you should remove the explicit uno-sdk compile tag, as ImGui comes with its own, unless you really need it, in ehich case you should make sure you use the same version as your ImGui does. Second off, Kotlin ImGui requires LWJGL 3.2.2 as of now, so you will likely need to lower that until we fix that. Additionally, I recommend changing your ImGui version from 1.71 to `1.73-SNAPSHOT`, which is much more up to date. With those changes, you may be able to base your program off of the samples at [imgui-gl/src/test/kotlin/imgui/opengl3.kt](imgui-gl/src/test/kotlin/imgui/opengl3.kt). If these do not work, please let me know!

**Comment by elect86** [comment]
I just merged 1.73 on the master, give it a try and let us know if the problem persists

**Comment by elect86** [comment]
closing for inactivity

**Comment by tdgroot** [comment]
@elect86 sorry for getting back to you so late. 

I've continued working with just LWJGL, but after getting quite some work done I'd really like to be able to use some sort of imgui. 

So I've tried the new release of imgui 1.74, but now I'm running into other problems:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void glm_.vec2.Vec2i.<init>(int, int, int, kotlin.jvm.internal.DefaultConstructorMarker)'
	at uno.glfw.GlfwWindow.<init>(GlfwWindow.kt:68)
	at ... KEngine.<init>(KEngine.kt:61)
   ...
```

Perhaps we can investigate this problem together over Discord?

**Comment by elect86** [comment]
Sure, tell me how (I'm used to Slack)

**Comment by elect86** [comment]
I think this is resolved
