### ISSUE TITLE
NoSuchMethodError: Library.loadNative in imm with jdk8 branch

### ISSUE THREAD

**Issue by Wicpar** [kotlin-graphics/imgui#125]
```
java.lang.NoSuchMethodError: org.lwjgl.system.Library.loadNative(Ljava/lang/String;)Lorg/lwjgl/system/SharedLibrary;
	at imgui.windowsIme.imm.<clinit>(imm.kt:15)
	at imgui.ImGuiStaticFunctions$imeSetInputScreenPosFn_Win32$1.invoke(static funcs.kt:1082)
	at imgui.ImGuiStaticFunctions$imeSetInputScreenPosFn_Win32$1.invoke(static funcs.kt)
	at imgui.imgui.imgui_main$DefaultImpls.endFrame(main.kt:347)
	at imgui.ImGui.endFrame(imgui.kt:95)
	at imgui.imgui.imgui_main$DefaultImpls.render(main.kt:423)
	at imgui.ImGui.render(imgui.kt:95)
```

I am trying to get the library to work with the JDK 8

here is my config: (gradle 5.5)
```groovy

project.ext.lwjglVersion = "3.2.3"
project.ext.jomlVersion = "1.9.11"

def natives = ["windows", "linux", "macos"]
def lwjgl = ["", "-glfw", "-opengl", "-stb", "-jemalloc", "-openal"]
def imgui = ["gl", "core", "glfw"]

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.2'
    implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")
    lwjgl.each { lib ->
        implementation ("org.lwjgl:lwjgl$lib:$lwjglVersion") {
            version {
                strictly lwjglVersion
            }
        }
        natives.each { os ->
            runtimeOnly ("org.lwjgl:lwjgl$lib:$lwjglVersion:natives-$os") {
                version {
                    strictly lwjglVersion
                }
            }
        }
    }
    implementation ('com.github.kotlin-graphics.glm:glm:jdk8-SNAPSHOT')
    implementation ('com.github.kotlin-graphics:gln:jdk8-SNAPSHOT') {
        exclude group: 'com.github.kotlin-graphics', module: 'gli'
    }
    implementation('com.github.wicpar:gli:jdk8-SNAPSHOT') {
        exclude group: 'com.github.kotlin-graphics', module: 'kool'
    }
    implementation('com.github.kotlin-graphics:uno-sdk:jdk8-SNAPSHOT') {
        exclude group: 'com.github.kotlin-graphics', module: 'gli'
        exclude group: 'com.github.kotlin-graphics.uno-sdk', module: 'uno-awt'
        exclude group: 'com.github.kotlin-graphics.uno-sdk', module: 'uno-vk'
    }
    imgui.each {
        compile ("com.github.kotlin-graphics.imgui:imgui-$it:jdk8-SNAPSHOT") {
            exclude group: 'com.github.kotlin-graphics.uno-sdk', module: 'uno-awt'
            exclude group: 'com.github.kotlin-graphics.uno-sdk', module: 'uno-vk'
            exclude group: 'com.github.kotlin-graphics', module: 'gli'
            exclude group: 'com.lwjgl', module: 'gli'
        }
    }
    implementation "org.joml:joml:${jomlVersion}"
    implementation group: 'com.google.code.gson', name: 'gson', version: '2.8.5'
    implementation "com.code-disaster.steamworks4j:steamworks4j:1.8.0"
}
```

it's quite tricky, the dependency `com.github.kotlin-graphics:gli:jdk8-SNAPSHOT` did not resolve so i had to do a fork,

Some other dependencies of the jdk8 branch had non JDK8 depenencies so i had to add them manually as well

**Comment by elect86** [comment]
I can add you as well, so you can take care of it, if you want :)

**Comment by Wicpar** [comment]
I got it to work, there was a lwjgl version mismatch between the different jdk8-snapshot dependencies. I don't know how to do proper releases with jitpack, especially from a branch.

**Comment by elect86** [comment]
You simply push, copy the commit id, paste as a dependency, refresh, jitpack will start building and deliver as soon as possible

**Comment by Wicpar** [comment]
yes i see, i mean make a proper release like "1.0.0-jdk8" so i don't have to put the commit id as dependency, or have the jdk8-SNAPSHOT update and break the dependency chain.
I got it barely to work, i am in quite a rush on another project as well, i'll look into it once i'm done with that.

**Comment by elect86** [comment]
publish a release here on GH and put the dependency on the tag (you can check everything [here](https://jitpack.io/#kotlin-graphics/imgui))

>I got it barely to work, i am in quite a rush on another project as well, i'll look into it once i'm done with that.

I can start adding you to the needed projects, so you can immediately be operative when you'll look into that, if you want

**Comment by Wicpar** [comment]
that'd be great, thanks
