### ISSUE TITLE
Fat jar fails loading

### ISSUE THREAD

**Issue by Sylvyrfysh** [kotlin-graphics/imgui#16]
Fat jar 1.52 works fine, but 1.53 wip beta 03 fails to load with

`[LWJGL] Version: 3.1.5 SNAPSHOT

[LWJGL] 	 OS: Windows 10 v10.0

[LWJGL] 	JRE: 1.8.0_144 amd64

[LWJGL] 	JVM: Java HotSpot(TM) 64-Bit Server VM v25.144-b01 by Oracle Corporation

[LWJGL] Loading library (system): lwjgl

[LWJGL] 	lwjgl.dll not found in java.library.path

[LWJGL] Failed to load a library. Possible solutions:

	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.

	b) Add the JAR that contains the shared library to the classpath.

Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll

	at org.lwjgl.system.Library.loadSystem(Library.java:146)

	at org.lwjgl.system.Library.loadSystem(Library.java:66)

	at org.lwjgl.system.Library.<clinit>(Library.java:49)

	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:60)

	at uno.buffer.BufferKt.intBufferBig(buffer.kt:21)

	at imgui.impl.LwjglGL3.<clinit>(LwjglGL3.kt:63)

	at com.sylvyrfysh.monerowallet.MoneroWalletMain.<init>(MoneroWalletMain.java:23)

	at com.sylvyrfysh.monerowallet.MoneroWalletMain.main(MoneroWalletMain.java:18)

`

**Comment by elect86** [comment]
Sorry, I wanted to comment but I pressed on the wrong button..

I tested and I had the same, I published a new release reverting the `testRuntime` native to `runtime` in `build.gradle`

**Comment by elect86** [comment]
[Here](https://github.com/kotlin-graphics/imgui/releases/tag/v1.53wip-beta04) you go

**Comment by elect86** [comment]
There is another important push in this regards, by TheMrMilchmann
