### ISSUE TITLE
Recent fat jar loads fail

### ISSUE THREAD

**Issue by Sylvyrfysh** [kotlin-graphics/imgui#18]
I have tried building my own, and using the provided jars, but all the recent fat jars fail. 
The issue is with the GLFW library, setting the  uno-sdk to sha 040f71aaf6ac580925f66cb86bbb3a98d40b0646 (right before changing getTime to float) and then fixing callbacks works. I cannot seem to fix this, traces are
```
Exception in thread "Thread-0" java.lang.NoSuchMethodError: uno.glfw.GlfwWindow.setScrollCallBack(Lkotlin/jvm/functions/Function2;)V
	at imgui.impl.LwjglGL3.init(LwjglGL3.kt:103)
```
Setting init's second argument to false, therefore bypassing scrollCallback brings up
```
Exception in thread "Thread-0" java.lang.NoSuchMethodError: uno.glfw.glfw.getTime()F
	at imgui.impl.LwjglGL3.newFrame(LwjglGL3.kt:127)
```

**Comment by elect86** [comment]
Hi, 

As slacked, the jitpack issue is now solved and I pushed
