### ISSUE TITLE
switch fullscreen/window mode crash imgui

### ISSUE THREAD

**Issue by Catvert** [kotlin-graphics/imgui#26]
Hi !
When I switch the game to full screen in game, imgui crash with this error: 
`Exception in thread "main" kotlin.KotlinNullPointerException
	at imgui.imgui.imgui_internal$DefaultImpls.getCurrentWindow(internal.kt:105)
	at imgui.ImGui.getCurrentWindow(imgui.kt:27)
	at imgui.imgui.imgui_parametersStacks$DefaultImpls.popItemWidth(parameters stacks.kt:230)
	at imgui.ImGui.popItemWidth(imgui.kt:27)
	at be.catvert.pc.scenes.MainMenuScene$drawSettingsWindow$$inlined$with$lambda$1.invoke(MainMenuScene.kt:257)
	at be.catvert.pc.scenes.MainMenuScene$drawSettingsWindow$$inlined$with$lambda$1.invoke(MainMenuScene.kt:26)
	at be.catvert.pc.utility.ImGuiHelper.withCenteredWindow(ImGuiHelper.kt:381)
	at be.catvert.pc.utility.ImGuiHelper.withCenteredWindow$default(ImGuiHelper.kt:377)
	at be.catvert.pc.scenes.MainMenuScene.drawSettingsWindow(MainMenuScene.kt:192)
	at be.catvert.pc.scenes.MainMenuScene.drawUI(MainMenuScene.kt:54)
	at be.catvert.pc.scenes.MainMenuScene.render(MainMenuScene.kt:42)
	at be.catvert.pc.scenes.SceneManager.render(SceneManager.kt:96)
	at be.catvert.pc.PCGame.render(PCGame.kt:101)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:392)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at be.catvert.pc.Lwjgl3Launcher.main(Lwjgl3Launcher.kt:34)
`

I tried several solutions to fix the problem, like relaunching a new frame, end the window before the switch, ... but nothing works: (

**Comment by Sylvyrfysh** [comment]
When you end the window, do you continue calling imgui until the render call, or immediately call render/newFrame?

If you don't, could you:

1. Try calling render before you fullscreen and newFrame after (`imgui.render(); app.fullscreen(); imgui.newFrame()`). This will cause 2 junk frames, but is preferable to a crash.
2. Create a simple example where the crash occurs so I can try it? The smaller the better

**Comment by Catvert** [comment]
Your solution works, thanks!
