### ISSUE TITLE
LibGDX example not working

### ISSUE THREAD

**Issue by klianc09** [kotlin-graphics/imgui#38]
Hi, I'd like to use imgui with LibGDX, but couldn't find any minimal example. And the current steps in the Wiki do not work for me.

My current code is in this repository (and I'd like to be able to provide a working minimal example project for others too):
https://github.com/klianc09/imguiexample

I added the dependencies to the generated project, as documented in the Wiki. 
However when trying to run I get the following error message:

`
$ ./gradlew lwjgl3:run
Configuration on demand is an incubating feature.
Download https://jitpack.io/com/github/kotlin-graphics/imgui/-SNAPSHOT/maven-metadata.xml

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':core:compileClasspath'.
> Could not find com.github.kotlin-graphics:imgui:-SNAPSHOT.
  Searched in the following locations:
      file:/home/toni/.m2/repository/com/github/kotlin-graphics/imgui/-SNAPSHOT/maven-metadata.xml
      file:/home/toni/.m2/repository/com/github/kotlin-graphics/imgui/-SNAPSHOT/imgui--SNAPSHOT.pom
      file:/home/toni/.m2/repository/com/github/kotlin-graphics/imgui/-SNAPSHOT/imgui--SNAPSHOT.jar
      https://repo1.maven.org/maven2/com/github/kotlin-graphics/imgui/-SNAPSHOT/maven-metadata.xml
      https://repo1.maven.org/maven2/com/github/kotlin-graphics/imgui/-SNAPSHOT/imgui--SNAPSHOT.pom
      https://repo1.maven.org/maven2/com/github/kotlin-graphics/imgui/-SNAPSHOT/imgui--SNAPSHOT.jar
      https://jcenter.bintray.com/com/github/kotlin-graphics/imgui/-SNAPSHOT/maven-metadata.xml
      https://jcenter.bintray.com/com/github/kotlin-graphics/imgui/-SNAPSHOT/imgui--SNAPSHOT.pom
      https://jcenter.bintray.com/com/github/kotlin-graphics/imgui/-SNAPSHOT/imgui--SNAPSHOT.jar
      https://oss.sonatype.org/content/repositories/snapshots/com/github/kotlin-graphics/imgui/-SNAPSHOT/maven-metadata.xml
      https://oss.sonatype.org/content/repositories/snapshots/com/github/kotlin-graphics/imgui/-SNAPSHOT/imgui--SNAPSHOT.pom
      https://oss.sonatype.org/content/repositories/snapshots/com/github/kotlin-graphics/imgui/-SNAPSHOT/imgui--SNAPSHOT.jar
      https://jitpack.io/com/github/kotlin-graphics/imgui/-SNAPSHOT/maven-metadata.xml
      https://jitpack.io/com/github/kotlin-graphics/imgui/-SNAPSHOT/imgui--v1.60wip-beta-02-g789514e-20.pom
      https://jitpack.io/com/github/kotlin-graphics/imgui/-SNAPSHOT/imgui--v1.60wip-beta-02-g789514e-20.jar
      https://dl.bintray.com/kotlin/kotlin-dev/com/github/kotlin-graphics/imgui/-SNAPSHOT/maven-metadata.xml
      https://dl.bintray.com/kotlin/kotlin-dev/com/github/kotlin-graphics/imgui/-SNAPSHOT/imgui--SNAPSHOT.pom
      https://dl.bintray.com/kotlin/kotlin-dev/com/github/kotlin-graphics/imgui/-SNAPSHOT/imgui--SNAPSHOT.jar
  Required by:
      project :core

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 16s
1 actionable task: 1 executed
`

Any pointers would be appreciated.

**Comment by kevinmurphy678** [comment]
Having this same issue. It can't find the library on the repo any more with -SNAPSHOT. A working libgdx project example would be helpful

**Comment by kevinmurphy678** [comment]
Try (in core)


```
 compile "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
 compile "com.github.kotlin-graphics:imgui:789514ef0598386fd1431e92b916fed96c82da66"
 compile group: 'org.lwjgl', name: 'lwjgl-stb', version: 'SNAPSHOT'
 compile "com.badlogicgames.gdx:gdx:$gdxVersion"
```

**Comment by kevinmurphy678** [comment]
Okay so I have a working project on windows over here if you want to take a look:

https://github.com/kevinmurphy678/BezierProject2



The lwjgl-stb natives dll kept giving me trouble so I just downloaded the jar and imported it manually. Everything seems to be working now. It's not ideal but it works

**Comment by klianc09** [comment]
I looked at your BezierProject2, and providing the specific version of the imgui dependency did the trick. Apparently "-SNAPSHOT" doesn't work at the moment? I did not need to add any lwjgl-stb natives though (on linux).
So the question for me is: Is "-SNAPSHOT" no longer recommended/supported? And what version should we use instead, if so?

Slightly off-topic: my PC doesn't support GLSL 1.50, so I got the following error:

    Caused by: java.lang.Error: 0:3(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES
        at gln.program.Program$Companion.createShaderFromSource(program.kt:219)
        at imgui.impl.LwjglGL3.createDeviceObjects(LwjglGL3.kt:157)
        ...

Since imgui doesn't seem to utilize GLSL 1.5 features, I recompiled imgui changing the "#version 150" line in the shaders to "#version 130" and with that I can run your project without a problem.

I guess I should open a new issue or a pull request, asking to lower the GLSL requirement to 1.3, or at least give us an option to lower it to 1.3.

**Comment by Sylvyrfysh** [comment]
GLSL 150 was chosen since about a week ago, it was 300, but was lowered for more hardware at the expense of a little more code. I'll figure out the lowest it can go

**Comment by elect86** [comment]
@klianc09  I never really relied on the `-SNAPSHOT` because since I always work on latest commits, I want to be notified if the commit I'm looking for is not available

Anyway, this looks like a `jitpack` issue, you may want to ask over there what's wrong ([here exactly](https://github.com/jitpack/jitpack.io/issues))

@kevinmurphy678 any news on your issue? It's very weird.. same project, different machines, different behaviors?

@klianc09, if you are on java, you can set the glsl version like [here](https://github.com/kotlin-graphics/imgui/blob/master/src/test/java/imgui/Test_lwjgl.java#L32) (you also need the last entry of the imports)

**Comment by klianc09** [comment]
> "... since I always work on latest commits, I want to be notified if the commit I'm looking for is not available"

@elect86 I'm not sure what you mean by that :/

But thanks for pointing me to jitpack. It should of course be "\<branchname\>-SNAPSHOT" not just "-SNAPSHOT" like the wiki says. * *facepalm* * 
So in this case I used the version "master-SNAPSHOT" and it works nicely.
Should I fix the wiki or does somebody else do that?

Also that Java example is really good. I wanted to say you add it to the Readme and Wiki, but then I saw that it actually is in the Readme, just hidden really far down... I would suggest the links to the demos should be above the wall of screenshots.

**Comment by elect86** [comment]
> I'm not sure what you mean by that :/

I mean, lately whenever I need something in the lower libraries (gli, glm, uno), I implement that, push, copy that commit id and pull it back wherever I needed that. 

>But thanks for pointing me to jitpack. It should of course be "<branchname>-SNAPSHOT" not just "-SNAPSHOT" like the wiki says. * facepalm *

Weird, I recall `-SNAPSHOT` being a shortcut of `<branchname>-SNAPSHOT`, maybe I'm wrong

> Should I fix the wiki or does somebody else do that?
> Also that Java example is really good. I wanted to say you add it to the Readme and Wiki, but then I saw that it actually is in the Readme, just hidden really far down... I would suggest the links to the demos should be above the wall of screenshots.

Sure, this is super ultra welcome!

I sent you an invite :)

Do whatever you think is best, just drop a line here to report once you are done 

Ps: considering closing the issue if solved

**Comment by elect86** [comment]
Exactly, thanks Kevin

You could do something like [this](https://github.com/kotlin-graphics/imgui/blob/master/src/test/java/imgui/Test_lwjgl.java#L21-L24) on top

**Comment by klianc09** [comment]
Thanks people! Sorry for asking trivial questions...

**Comment by elect86** [comment]
Don't worry

**Comment by klianc09** [comment]
I fixed the links to the tests in the README.md and moved the Gallery lower.
5bdb7b574f686eca6a8831724152824088a105d4
6e668d51369a3cdafcd515984925296ea36c2644

I haven't changed much in the wiki yet, since the info there is correct. (And I'm not sure what caused the '-SNAPSHOT' not working for me.) However I did add a small section from the README to the wiki starting page, so there is more relevant information for people that want to learn how to use ImGui.
