### ISSUE TITLE
Crash on color picker

### ISSUE THREAD

**Issue by wrymn** [kotlin-graphics/imgui#41]
When opening color picker and right-mouse clicking into color area to change "color pick mode", the application crashes on

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at imgui.imgui.imgui_widgetsColorEditorPicker$DefaultImpls.colorPicker4(widgets colorEditorPicker.kt:334)
	at imgui.ImGui.colorPicker4(imgui.kt:44)
	at imgui.imgui.imgui_widgetsColorEditorPicker$DefaultImpls.colorPicker4$default(widgets colorEditorPicker.kt:299)
	at imgui.imgui.imgui_widgetsText$Companion.colorPickerOptionsPopup(widgets text.kt:266)
	at imgui.imgui.imgui_widgetsColorEditorPicker$DefaultImpls.colorPicker4(widgets colorEditorPicker.kt:313)
	at imgui.ImGui.colorPicker4(imgui.kt:44)
	at imgui.imgui.imgui_widgetsColorEditorPicker$DefaultImpls.colorEdit4(widgets colorEditorPicker.kt:217)
	at imgui.ImGui.colorEdit4(imgui.kt:44)
	at imgui.imgui.imgui_widgetsColorEditorPicker$DefaultImpls.colorEdit4(widgets colorEditorPicker.kt:99)
```

**Comment by elect86** [comment]
it should be fixed now, although there are some issue with the mouse, give it a try

**Comment by elect86** [comment]
It should be completely fixed now, also the mouse movement

If you confirm, you can close it

**Comment by elect86** [comment]
I'll close it, if still there, re-open
