### ISSUE TITLE
kotlin.NotImplementedError: An operation is not implemented.

### ISSUE THREAD

**Issue by Ealrann** [kotlin-graphics/imgui#43]
Hello,

I got a recurring error when I use the colorButton: If I drag and drop (in fact if I move too fast when I click, whatever) it, I will got the following exception: 
```
Exception in thread "main" kotlin.NotImplementedError: An operation is not implemented.
	at imgui.imgui.imgui_dragAndDrop$DefaultImpls.setDragDropPayload(drag & Drop.kt:126)
	at imgui.ImGui.setDragDropPayload(imgui.kt:45)
	at imgui.imgui.imgui_widgetsColorEditorPicker$DefaultImpls.colorButton(widgets colorEditorPicker.kt:646)
	at imgui.ImGui.colorButton(imgui.kt:45)
	at org.sheepy.vulkan.sand.graphics.SandUIDescriptor.newFrame(SandUIDescriptor.java:110)
	at org.sheepy.vulkan.imgui.ImGuiPipeline.newFrame(ImGuiPipeline.java:377)
	at org.sheepy.vulkan.sand.pipelinepool.RenderPipelinePool.execute(RenderPipelinePool.java:74)
	at org.sheepy.vulkan.sand.SandApplication.drawFrame(SandApplication.java:169)
	at org.sheepy.vulkan.VulkanApplication.mainLoop(VulkanApplication.java:125)
	at org.sheepy.vulkan.sand.SandApplication.mainLoop(SandApplication.java:128)
	at org.sheepy.vulkan.VulkanApplication.run(VulkanApplication.java:63)
	at org.sheepy.vulkan.sand.SandApplication.main(SandApplication.java:178)
```
Not a big problem, I just open an issue to track it.

I use the last Snapshot "v1.62-beta-02".

**Comment by elect86** [comment]
Yeah, dragAndDrop is kind of tricky, that's why I put a `TODO()` in the code, hoping that I'd fix that before anyone trigger that. But I was wrong :D

Try 3653ce4, drag and drop is still bugged, but at least it shouldn't throw anything

**Comment by Ealrann** [comment]
Thank you very much, it does the trick :+1:
