### ISSUE TITLE
So this crashes

### ISSUE THREAD

**Issue by xyzyulo** [kotlin-graphics/imgui#44]
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\br3nn\AppData\Local\Temp\lwjglbr3nn\3.1.7-SNAPSHOT\lwjgl.dll: Can't load IA 32-bit .dll on a Intel 64-bit platform
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.lwjgl.system.Library.loadSystem(Library.java:162)
	at org.lwjgl.system.Library.loadSystem(Library.java:152)
	at org.lwjgl.system.Library.loadSystem(Library.java:116)
	at org.lwjgl.system.Library.loadSystem(Library.java:67)
	at org.lwjgl.system.Library.<clinit>(Library.java:50)
	at org.lwjgl.system.MemoryAccessJNI.<clinit>(MemoryAccessJNI.java:13)
	at org.lwjgl.system.Pointer.<clinit>(Pointer.java:26)
	at org.lwjgl.system.Platform.mapLibraryNameBundled(Platform.java:80)
	at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:665)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.getInt(Field.java:574)
	at org.lwjgl.system.APIUtil.apiClassTokens(APIUtil.java:308)
	at uno.glfw.glfw.<clinit>(glfw.kt:77)
	at Poop.<init>(Poop.java:26)
	at Poop.main(Poop.java:18)

**Comment by fricking** [comment]
ok

**Comment by fricking** [comment]
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/lwjgl/system/APIUtil.apiArray(Lorg/lwjgl/system/MemoryStack;[J)J @43: invokestatic
  Reason:
    Type 'org/lwjgl/PointerBuffer' (current frame, stack[0]) is not assignable to 'org/lwjgl/system/CustomBuffer'
  Current Frame:
    bci: @43
    flags: { }
Disconnected from the target VM, address: '127.0.0.1:51701', transport: 'socket'
    locals: { 'org/lwjgl/system/MemoryStack', '[J', 'org/lwjgl/PointerBuffer' }
    stack: { 'org/lwjgl/PointerBuffer' }
  Bytecode:
    0x0000000: 2a2b beb6 0080 4d2b 4e2d be36 0403 3605
    0x0000010: 1505 1504 a200 162d 1505 2f37 062c 1606
    0x0000020: b600 8157 8405 01a7 ffe9 2cb8 0082 ad  
  Stackmap Table:
    full_frame(@16,{Object[#283],Object[#284],Object[#285],Object[#284],Integer,Integer},{})
    chop_frame(@42,3)

	at uno.glfw.glfw.<clinit>(glfw.kt:77)
	at Test_lwjgl.<init>(Test_lwjgl.java:30)
	at Test_lwjgl.main(Test_lwjgl.java:25)

Process finished with exit code 1

**Comment by Sylvyrfysh** [comment]
Can you post code?

**Comment by elect86** [comment]
You are likely mixing JARs/natives from different versions..?

**Comment by Sylvyrfysh** [comment]
Hi! Friendly reminder that there has been no activity here for over a month and this appears to be fixed. If you wish to keep this open, please respond with what still is an issue, or this will be closed in a week. Thanks!
