### ISSUE TITLE
Crashes in style editor

### ISSUE THREAD

**Issue by chrjen** [kotlin-graphics/imgui#45]
This is using v1.62-beta-02.

In the demo window if you go (Help > Style Editor > Rendering) then click *and drag* the Curve Tesselation Tolerance button I crash with the following exception.

```
Exception in thread "hmd-renderer" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:44)
	at java.base/java.lang.String.charAt(String.java:704)
	at imgui.imgui.imgui_internal$DefaultImpls.parseFormatFindStart(internal.kt:3283)
	at imgui.ImGui.parseFormatFindStart(imgui.kt:45)
	at imgui.imgui.imgui_internal$Companion.roundScalarWithFormat(internal.kt:3459)
	at imgui.imgui.imgui_main$Companion.dragBehaviorT(main.kt:862)
	at imgui.imgui.imgui_internal$DefaultImpls.dragBehavior(internal.kt:1509)
	at imgui.ImGui.dragBehavior(imgui.kt:45)
	at imgui.imgui.imgui_widgetsDrag$DefaultImpls.dragScalar(widgets drags.kt:266)
	at imgui.ImGui.dragScalar(imgui.kt:45)
	at imgui.imgui.imgui_widgetsDrag$DefaultImpls.dragFloat(widgets drags.kt:58)
	at imgui.ImGui.dragFloat(imgui.kt:45)
	at imgui.imgui.demo.StyleEditor.invoke(ExampleApp.kt:1138)
	at imgui.imgui.demo.StyleEditor.invoke$default(ExampleApp.kt:1090)
	at imgui.imgui.demo.ExampleApp.invoke(ExampleApp.kt:155)
	at imgui.imgui.imgui_demoDebugInformations$DefaultImpls.showDemoWindow(demo debug informations.kt:89)
	at imgui.ImGui.showDemoWindow(imgui.kt:45)
	at imgui.imgui.imgui_demoDebugInformations$DefaultImpls.showDemoWindow(demo debug informations.kt:85)
	at imgui.ImGui.showDemoWindow(imgui.kt:45)
	at com.chrjen.pluto.gui.VRScene$VRRenderer.loop(VRScene.java:743)
	at com.chrjen.pluto.gui.VRScene$VRRenderer.lambda$run$0(VRScene.java:260)
	at uno.glfw.GlfwWindow.loop(GlfwWindow.kt:492)
```

Likewise if you go  (Help > Style Editor > Fonts > Glyphs) I crash with get he following exception.
```
Exception in thread "hmd-renderer" java.lang.IndexOutOfBoundsException: Index -1 out-of-bounds for length 225
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:440)
	at imgui.Font.findGlyphNoFallback(font.kt:978)
	at imgui.Font.findGlyphNoFallback(font.kt:977)
	at imgui.imgui.demo.StyleEditor.invoke(ExampleApp.kt:1275)
	at imgui.imgui.demo.StyleEditor.invoke$default(ExampleApp.kt:1090)
	at imgui.imgui.demo.ExampleApp.invoke(ExampleApp.kt:155)
	at imgui.imgui.imgui_demoDebugInformations$DefaultImpls.showDemoWindow(demo debug informations.kt:89)
	at imgui.ImGui.showDemoWindow(imgui.kt:45)
	at imgui.imgui.imgui_demoDebugInformations$DefaultImpls.showDemoWindow(demo debug informations.kt:85)
	at imgui.ImGui.showDemoWindow(imgui.kt:45)
	at com.chrjen.pluto.gui.VRScene$VRRenderer.loop(VRScene.java:743)
	at com.chrjen.pluto.gui.VRScene$VRRenderer.lambda$run$0(VRScene.java:260)
	at uno.glfw.GlfwWindow.loop(GlfwWindow.kt:492)
	at com.chrjen.pluto.gui.VRScene$VRRenderer.run(VRScene.java:259)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by elect86** [comment]
It should be fixed.

If it"s not just reopen
