### ISSUE TITLE
Crash in vertical sliders in demo window

### ISSUE THREAD

**Issue by chrjen** [kotlin-graphics/imgui#46]
This is using v1.62-beta-02.

In the demo window if I go (Widgets > Vertical Sliders) and try to move any of the sliders I get the following exception.

```
Exception in thread "hmd-renderer" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:44)
	at java.base/java.lang.String.charAt(String.java:704)
	at imgui.imgui.imgui_internal$DefaultImpls.parseFormatFindStart(internal.kt:3283)
	at imgui.ImGui.parseFormatFindStart(imgui.kt:45)
	at imgui.imgui.imgui_internal$Companion.roundScalarWithFormat(internal.kt:3459)
	at imgui.imgui.imgui_internal$DefaultImpls.sliderBehaviorT(internal.kt:1972)
	at imgui.ImGui.sliderBehaviorT(imgui.kt:45)
	at imgui.imgui.imgui_internal$DefaultImpls.sliderBehavior(internal.kt:1548)
	at imgui.ImGui.sliderBehavior(imgui.kt:45)
	at imgui.imgui.imgui_widgetsSliders$DefaultImpls.vSliderScalar(widgets sliders.kt:258)
	at imgui.ImGui.vSliderScalar(imgui.kt:45)
	at imgui.imgui.imgui_widgetsSliders$DefaultImpls.vSliderFloat(widgets sliders.kt:221)
	at imgui.ImGui.vSliderFloat(imgui.kt:45)
	at imgui.imgui.imgui_widgetsSliders$DefaultImpls.vSliderFloat$default(widgets sliders.kt:220)
	at imgui.imgui.demo.widgets.invoke(widgets.kt:987)
	at imgui.imgui.demo.ExampleApp.invoke(ExampleApp.kt:241)
	at imgui.imgui.imgui_demoDebugInformations$DefaultImpls.showDemoWindow(demo debug informations.kt:89)
	at imgui.ImGui.showDemoWindow(imgui.kt:45)
	at imgui.imgui.imgui_demoDebugInformations$DefaultImpls.showDemoWindow(demo debug informations.kt:85)
	at imgui.ImGui.showDemoWindow(imgui.kt:45)
	at com.chrjen.pluto.gui.VRScene$VRRenderer.loop(VRScene.java:748)
	at com.chrjen.pluto.gui.VRScene$VRRenderer.lambda$run$0(VRScene.java:260)
	at uno.glfw.GlfwWindow.loop(GlfwWindow.kt:492)
	at com.chrjen.pluto.gui.VRScene$VRRenderer.run(VRScene.java:259)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by elect86** [comment]
I"ll fix the last one later, I have to exit now

Reopen if still there
