### ISSUE TITLE
ImGui with Libgdx on Mac OS X

### ISSUE THREAD

**Issue by alex-dorokhov** [kotlin-graphics/imgui#55]
I'm going to build an editor for my game on Libgdx and found that imgui can help a lot in that.
My game is targeting Open GL ES 2.0 devices (including mobile phones). The editor should be able to run on Mac OS X and Windows.
I was able to run Lwjgl3 implementation of ImGui together with a simple libgdx project after several hours of trials and errors, but I see which troubles will I meet, when I try to integrate ImGui into existing project.

Points:
1. Current ImGui implementation is based on GL3.
2. That means that I have to configure Lwjgl to use OpenGL 3.2 API
3. Once I configure it to use OpenGL 3.2 on Mac OS X,  there seems to be no way to use earlier versions of OpenGL.
4. Shader of LibGDX/SpriteBatch is not compatible with OpenGL 3.2 API (I had to rewrite it to use 'in' and 'out' instead of 'attribute' and 'varying')
5. I have custom shaders in my game and they are targeting OpenGL ES 2.0. That means I can't test my shaders in the editor (and I have to find workarounds, like automatically rewrite old shaders to use in/out, when I run it on desktop)
6. All that means that I can't use OpenGL 3.2 API and have to stick to OpenGL 2.0 API.
7. As I can see it is big stop for LibGDX users (probably the largest set of potential users of ImGui)

Questions:
1. Do I miss something?
2. If I don't miss, is it a lot of work to add an implementation for OpenGL 2.0 in ImGui?

**Comment by alex-dorokhov** [comment]
Hi Giuseppe,

That is good to know! I need it for Lwjgl only.

OpenGL 2.0 is a superset of GLES 2.0, so it is basically just a matter of using OpenGL 2.0 API with Lwjgl, as I understand.

Are you going to do that any time soon?

**Comment by elect86** [comment]
I can try this this evening or in the weekend if I make it...

If you want to try yourself and push it, don't hesitate :)

**Comment by alex-dorokhov** [comment]
I can try as well, it doesn't look like a lot of code. If you give a chance and support, I will try it next days :)

**Comment by elect86** [comment]
Sure, I'll be here! :)

**Comment by Sylvyrfysh** [comment]
Hi! Friendly reminder that there has been no activity here for over a month and this appears to be fixed. If you wish to keep this open, please respond with what still is an issue, or this will be closed in a week. Thanks!

**Comment by elect86** [comment]
Hi Alex, 

@Sylvyrfysh implemented the GL2 backend, you may want to give it a [try](https://github.com/kotlin-graphics/imgui/tree/ImplGL2)

**Comment by alex-dorokhov** [comment]
Hi! Sorry for duplicate, but I've also in answered in #72.

I've tried the latest version from 'ImplGL2' branch (with libgdx 1.9.8 though) and got this stacktrace: 
```
java.lang.Exception: ERROR: 0:7: Invalid storage qualifiers 'in' in global variable context
ERROR: 0:8: Invalid storage qualifiers 'in' in global variable context
ERROR: 0:9: Invalid storage qualifiers 'in' in global variable context
ERROR: 0:11: Invalid storage qualifiers 'out' in global variable context
ERROR: 0:12: Invalid storage qualifiers 'out' in global variable context
ERROR: 0:16: Use of undeclared identifier 'uv'
ERROR: 0:16: Use of undeclared identifier 'UV'
ERROR: 0:17: Use of undeclared identifier 'color'
ERROR: 0:17: Use of undeclared identifier 'Color'
ERROR: 0:18: Use of undeclared identifier 'Position'
�
	at gln.objects.GlShader$Companion.createFromSource-RHQEpZs(shader.kt:70)
	at imgui.impl.ImplGL2.createDeviceObjects(ImplGL2.kt:49)
	at imgui.impl.LwjglGlfw.newFrame(LwjglGlfw.kt:154)
	at imgui.impl.LwjglGlfw$Companion.newFrame(LwjglGlfw.kt:34)
```

**Comment by Sylvyrfysh** [comment]
Should be fixed in ImplGL2 commit [4b38958](https://github.com/kotlin-graphics/imgui/commit/4b389582325271908615168f51edd652f23a692e)

**Comment by Sylvyrfysh** [comment]
Hey Alex, I believe our implementation is mostly finished and bug-free. Can you confirm that things are working for you in this project, or did you abandon it?

**Comment by alex-dorokhov** [comment]
Hey, @Sylvyrfysh , the latest version is seems to be working fine. At least I was able to create windows, labels and texts. Thanks for your work!
I will now finally start to use the library :)
I guess the ticket can be closed now.
