### ISSUE TITLE
Can't type in input fields

### ISSUE THREAD

**Issue by vfmachado** [kotlin-graphics/imgui#63]
This is happened even on Demo App =/

There is an option to enable / disable keyboard with ImGUI?

I'm using LWJGL with OpenGL and GLFW.

**Comment by elect86** [comment]
Hi, quick info: my machine got broken, I'll be back asap

**Comment by elect86** [comment]
Sorry, try the update branch: e824187

**Comment by elect86** [comment]
I just merged it into the master, for info

**Comment by vfmachado** [comment]
Hello,

in previous version I was enabled to create the window context using the handler of Lwjgl GLFW implementation (long value). Like this:

lwjglGlfw.init(new GlfwWindow(window.getHandler()), true, GlfwClientApi.OpenGL);

In the new branch this methos isn't available. How can I do the same thing?

Thank you.

**Comment by elect86** [comment]
sorry, that was broken

233cff5d023d4329b7e82ea375178159d41f487b

**Comment by vfmachado** [comment]
Exception in thread "main" java.lang.NoSuchMethodError: org.lwjgl.system.MemoryUtil.memAddress(Ljava/nio/Buffer;)J
	at gln.GlnKt.<clinit>(gln.kt:168)
	at imgui.impl.ImplGL3.createFontsTexture(ImplGL3.kt:326)
	at imgui.impl.ImplGL3.createDeviceObjects(ImplGL3.kt:90)
	at imgui.impl.LwjglGlfw.newFrame(LwjglGlfw.kt:102)

**Comment by vfmachado** [comment]
Fixed updating lwjgl to 3.2.1 (same version of your project)

Really thanks, I appreciate your job

**Comment by elect86** [comment]
Glad you solved.

Thanks for the nice words 👍 

Consider closing if solved

**Comment by Sylvyrfysh** [comment]
Hi! Friendly reminder that there has been no activity here for over a month and this appears to be fixed. If you wish to keep this open, please respond with what still is an issue, or this will be closed in a week. Thanks!

**Comment by vfmachado** [comment]
Thank you for your support.
