### ISSUE TITLE
OpenGL Error (GL_INVALID_VALUE) at createFontsTexture

### ISSUE THREAD

**Issue by yuraj11** [kotlin-graphics/imgui#69]
Hi,
I am getting this error with LibGDX 1.9.9, imgui v1.67-beta-00
```
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.Exception: OpenGL Error (GL_INVALID_VALUE) at createFontsTexture
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
	at com.x.prototype.desktop.DesktopLauncher.main(DesktopLauncher.kt:17)
Caused by: java.lang.Exception: OpenGL Error (GL_INVALID_VALUE) at createFontsTexture
	at gln.GlnKt.checkError(gln.kt:78)
	at gln.GlnKt.checkError$default(gln.kt:61)
	at imgui.impl.ImplGL3.createFontsTexture(ImplGL3.kt:129)
	at imgui.impl.ImplGL3.createDeviceObjects(ImplGL3.kt:94)
	at imgui.impl.LwjglGlfw.newFrame(LwjglGlfw.kt:107)
	at com.x.prototype.screen.TileEditorScreen.show(TileEditorScreen.kt:23)
	at com.badlogic.gdx.Game.setScreen(Game.java:61)
	at com.x.prototype.App.setCurrentScreen(App.kt:32)
```

```
class TileEditorScreen(app: AppContext, val levelName: String, val loadMap: Boolean)
    : BaseScreen(app) {

    private lateinit var context: Context

    override fun show() {
        super.show()
        context = Context()
        LwjglGlfw.init(GlfwWindow.from((Gdx.graphics as Lwjgl3Graphics).window.windowHandle))
        ImGui.styleColorsDark()
    }

    override fun renderScene(delta: Float) {
        LwjglGlfw.newFrame()

        with(ImGui) {
            begin("Demo_0", booleanArrayOf(true), 0)
            text("Hello, world!")
            end()

            showDemoWindow(booleanArrayOf(true))

            render()

            drawData?.run {
                ImplGL3.renderDrawData(this)
            }
        }
    }

    override fun dispose() {
        LwjglGlfw.shutdown()
        context.shutdown()
    }
}
```

In BaseScreen I have this:
```
    final override fun render(delta: Float) {
        clearScreen()
        uiStage.act()
        app.soundManager.update()

        renderScene(delta)
        renderHud()
    }

    abstract fun renderScene(delta: Float)

    private fun renderHud() {
        uiStage.draw()
    }
```
It does not happen when I disable `renderHud` in `render` but It happens also when I add after renderScene just empty `batch.begin(); batch.end()` like  this:
```
abstract class BaseScreen(val app: AppContext) : com.badlogic.gdx.Screen, InputProcessor { //
   ...
   final override fun render(delta: Float) {
        ...
        renderScene(delta)
        batch.begin()
        batch.end()
}
```

In App I have this:
```
class App : Game(), AppContext {
    ...
    override var currentScreen: Screen
        get() = screen
        set(value) {
            if (screen != null) {
                screen.dispose()
            }
            setScreen(value)
        }
```
and I open screen like this:
```
        loadMap.onClick {
            app.currentScreen = TileEditorScreen(app, mapName.text, true)
        }
```

**Comment by Sylvyrfysh** [comment]
Can you create a minimal reproducible error? This means create a single file with the least amount needed to create the error. Otherwise, please link the repository.

**Comment by yuraj11** [comment]
[guitest.zip](https://github.com/kotlin-graphics/imgui/files/2856865/guitest.zip)
Here you are. Finally I was able to make demo with the issue.

**Comment by yuraj11** [comment]
I have managed to fix It in demo code:
BaseScreen:
```
    protected val batch = SpriteBatch()
    protected val uiStage = UserInterfaceStage(app, batch)
```
UserInterfaceStage:
```
class UserInterfaceStage(private val app: Application, batch: SpriteBatch) : Stage(ScreenViewport(OrthographicCamera()), batch)
```
When I use same batch Stage It works. Anyway I need to fix my architecture and create one SpriteBatch object for entire application and stages but still I am not sure what is actually causing this problem.

**Comment by Sylvyrfysh** [comment]
Thanks for sending this in. I was able to find that ImGui itself does not have any errors, rather I can guess that this is a LibGDX issue. If you call `glGetError()` at the beginning of `renderScene()` in `TestScreen`, the issue has already occurred. While ImGui intialization does occur before this, checking for GL errors returns nothing. This is likely a LibGDX issue or something you are doing yourself.

The reason this occurs to be an ImGui issue is simply because the first GL error check in the render loop is in ImGui, at createFontsTexture.

**Comment by yuraj11** [comment]
Yes that's possible. I have solved It by using only one Spritebatch for entire application. Thanks for your help.
