### ISSUE TITLE
Input long text problem

### ISSUE THREAD

**Issue by yuraj11** [kotlin-graphics/imgui#74]
Hi,
there is still issue with inputs (https://github.com/kotlin-graphics/imgui/issues/70#issuecomment-462955102 I have already latest repo changes)

![image](https://user-images.githubusercontent.com/5477518/52717167-bfc2d380-2fa0-11e9-9fb6-b662f395f374.png)

![image](https://user-images.githubusercontent.com/5477518/52717178-cc472c00-2fa0-11e9-8122-2ef0564419a2.png)

**Comment by yuraj11** [comment]
Also copy & paste causes sometime crash:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at imgui.imgui.imgui_internal$DefaultImpls.inputTextEx(internal.kt:2440)
	at imgui.ImGui.inputTextEx(imgui.kt:76)
	at imgui.imgui.imgui_internal$DefaultImpls.inputTextEx$default(internal.kt:2118)
	at imgui.imgui.widgets.inputKeyboard$DefaultImpls.inputText(inputKeyboard.kt:46)
	at imgui.ImGui.inputText(imgui.kt:76)
	at imgui.imgui.widgets.inputKeyboard$DefaultImpls.inputText$default(inputKeyboard.kt:42)
```

**Comment by yuraj11** [comment]
When I paste text into input:
![image](https://user-images.githubusercontent.com/5477518/52717414-5db69e00-2fa1-11e9-8c47-1e0049c0dbe2.png)

**Comment by Sylvyrfysh** [comment]
Can you send in a minimum reproducible build? I cannot get either error to trigger

**Comment by Sylvyrfysh** [comment]
The copy and paste is default behavior. It is because you have not specified the InputTextFlag.CallbackResize flag on your input box. This is done to prevent overcopies from a larger ImGui buffer into a smaller user buffer.

**Comment by yuraj11** [comment]
The funny thing is I can not simulate either by now. :laughing:

**Comment by yuraj11** [comment]
Ok I will close this issue for now and create a new one with demo If this issue will occur in future (or maybe not).
