### ISSUE TITLE
input* component bug

### ISSUE THREAD

**Issue by yuraj11** [kotlin-graphics/imgui#83]
Inputs does not work correctly with latest changes. When I change input value (programatically or with + - buttons) I don't see change - only when I directly click input then the value is refreshed and shows correct value.

**Comment by yuraj11** [comment]
Copy & Paste does not work with latest master changes:
```xception in thread "main" java.awt.datatransfer.UnsupportedFlavorException: Unicode String
	at sun.awt.datatransfer.SunClipboard.getData(SunClipboard.java:220)
	at imgui.imgui.imgui_internal$DefaultImpls.inputTextEx(internal.kt:2486)
	at imgui.ImGui.inputTextEx(imgui.kt:76)
	at imgui.imgui.widgets.inputKeyboard$DefaultImpls.inputText(inputKeyboard.kt:47)
	at imgui.ImGui.inputText(imgui.kt:76)
	at imgui.imgui.widgets.inputKeyboard$DefaultImpls.inputText$default(inputKeyboard.kt:43)
	at imgui.imgui.widgets.inputKeyboard$DefaultImpls.inputScalar(inputKeyboard.kt:176)
	at imgui.ImGui.inputScalar(imgui.kt:76)
	at imgui.imgui.widgets.inputKeyboard$DefaultImpls.inputFloat(inputKeyboard.kt:63)
	at imgui.ImGui.inputFloat(imgui.kt:76)
	at imgui.imgui.widgets.inputKeyboard$inputFloat$1.invoke(inputKeyboard.kt:58)
	at imgui.imgui.widgets.inputKeyboard$inputFloat$1.invoke(inputKeyboard.kt:39)
	at imgui.imgui.InternalKt.withFloat(internal.kt:3364)
	at imgui.imgui.widgets.inputKeyboard$DefaultImpls.inputFloat(inputKeyboard.kt:58)
	at imgui.ImGui.inputFloat(imgui.kt:76)
	at imgui.imgui.widgets.inputKeyboard$DefaultImpls.inputFloat$default(inputKeyboard.kt:58)
	at imgui.imgui.demo.showExampleApp.PropertyEditor.showDummyObject(PropertyEditor.kt:86)
	at imgui.imgui.demo.showExampleApp.PropertyEditor.invoke(PropertyEditor.kt:55)
	at imgui.imgui.demo.ExampleApp.invoke(ExampleApp.kt:92)
	at imgui.imgui.imgui_demoDebugInformations$DefaultImpls.showDemoWindow(demo debug informations.kt:105)
	at imgui.ImGui.showDemoWindow(imgui.kt:76)
	at imgui.gl.HelloWorld_lwjgl.mainLoop(test lwjgl.kt:126)
	at imgui.gl.HelloWorld_lwjgl.<init>(test lwjgl.kt:102)
	at imgui.gl.Test_lwjglKt.main(test lwjgl.kt:28)
	at imgui.gl.Test_lwjglKt.main(test lwjgl.kt)```

**Comment by Sylvyrfysh** [comment]
My mind is elsewhere as I try to move each backend into a different branch,
but I'll try to look into these this weekend. I'll also try to develop
better testing so that this didn't happen again. For now, do you know the
last commit it worked?

**Comment by yuraj11** [comment]
I am using 1591dcc and there It didn't crash for me.
But still copy & paste never worked for me. When I do CTRL+C or CTRL+X It does something but when I paste CTRL+V It pastes something different.

**Comment by elect86** [comment]
I reworked a little copy/pasting

I tested quickly `InputFloat`, by copy/pasting in imgui `0.123`, it looks fine

Waiting for further feedbacks, if any

**Comment by yuraj11** [comment]
Editing works correctly now but still copy & paste crashes on Linux (I haven't tested on mac). I read that this could be linux specific crash.

**Comment by elect86** [comment]
Which widget are you using? 

Does it crash when you copy in system and paste in imgui?

**Comment by yuraj11** [comment]
Copying from system and then pasting into inputText works correctly. But when I try to copy/cut inside inputText then It crashes.

**Comment by elect86** [comment]
I think I fixed but I'll let decide that to you

I played a little with it on Ubuntu and it looks fine

**Comment by yuraj11** [comment]
OK now It works correctly.

**Comment by elect86** [comment]
Ok, I'll close it then
