### ISSUE TITLE
OpenGL Error (GL_OUT_OF_MEMORY)  - Demo - Widgets - DataTypes - Drags and Sliders

### ISSUE THREAD

**Issue by Mr00Anderson** [kotlin-graphics/imgui#93]
**Issue**: 
Exception in thread "main" java.lang.Exception: OpenGL Error (GL_OUT_OF_MEMORY)

```
Exception in thread "main" java.lang.Exception: OpenGL Error (GL_OUT_OF_MEMORY) at createDeviceObject
	at gln.GlnKt.checkError(gln.kt:79)
	at gln.GlnKt.checkError$default(gln.kt:62)
	at imgui.impl.ImplGL3.createDeviceObjects(ImplGL3.kt:112)
	at imgui.impl.LwjglGlfw.newFrame(LwjglGlfw.kt:156)
	at imgui.gl.Test_lwjgl.mainLoop(Test_lwjgl.java:108)
	at imgui.gl.Test_lwjgl.lambda$new$0(Test_lwjgl.java:94)
	at uno.glfw.GlfwWindow.loop(GlfwWindow.kt:594)
	at imgui.gl.Test_lwjgl.<init>(Test_lwjgl.java:93)
	at imgui.gl.Test_lwjgl.main(Test_lwjgl.java:38)
```

This may only be an issue in the Demo. With the demo being the example/tutorial and use testing this will need to be pinned down. 

**Cause**
Unsure exact code line - Currently crashes after leaving the demo open for about 15-30 minutes. When the  - Demo - Widgets - DataTypes - Drags and Sliders is left open. I have left the demo open and walked away a few times to come back to the demo being closed. I have not had time to look through that area to see whats leaking or where. This has happened on my Windows 10 Desktop and Windows 10 Laptop.
![Screenshot 2019-05-13 14 57 40](https://user-images.githubusercontent.com/1356935/57646882-a295a500-758f-11e9-8760-738f0b17c253.png)

**Comment by Sylvyrfysh** [comment]
before or after the latest pull you sent in?

**Comment by Mr00Anderson** [comment]
This error occurred before any changes I had made. I just had wanted to make sure It kept occurring and make sure it was this section before putting the report in.

**Comment by elect86** [comment]
pull again, I forgot to undo a modification on gl3 sample for #88 

I'll try the same though

**Comment by Mr00Anderson** [comment]
Running test now on my laptop. Will let it run for an hour at the same spot.

**Comment by elect86** [comment]
Around 15m passed here, no crash and "Shared GPU memory usage" always 0.7-0.8/7.9 GB in Task Manager on my Intel 655.

Let's see what happen, I'll keep it running a little more

**Comment by Mr00Anderson** [comment]
I have not had either desktop or laptop crash. It must have been that. Will close this.
